[project]
name = "joker-2026"
version = "0.1.1"
authors = [{name = "Russell Taylor", email = "rdtaylorjr@gatech.edu"}, { name = "Adam Brikman", email = "abrikman3@gatech.edu" }, { name = "Prateek Awate", email = "pawate3@gatech.edu" }]
description = "DS@GT ARC CLEF 2026 JOKER Task 2 (pun translation) system"
readme = "README.md"
requires-python = ">=3.9"

[project.urls]
Homepage = "https://github.com/dsgt-arc/joker-2026"
Issues = "https://github.com/dsgt-arc/joker-2026/issues"
Joker = "https://www.joker-project.com/"
CLEF = "https://clef2026.clef-initiative.eu/"
